openapi: 3.0.2
info:
  version: 1.0.0
  title: BlackLotus
  description: "POR PONER"
servers:
  - url: 'http://127.0.0.1:8000/'
paths:
  /issue/:
    get:
      tags:
      - tweets
      summary: Retrieves all the Tweets
      operationId: getAllTweets
      parameters:
      - name: id
        in: query
        description: Optional id of the issue to retrieve
        required: false
        schema:
          type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
components:
  schemas:
    User:
      type: object
      properties:
        id:
            type: integer
            format: int64
            example: 2
        username:
            type: string
            minLength: 4
            example: 'TestSubject'
          
    Activity:
      type: object
      properties:
        creationdate:
          type: string
          format: date-time
        field:
          type: string
          minLength: 4
          example: 'status'
        change:
          tyoe: string
        old:
        user:
        issueChanged:
        objects:
    Issue:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 2
        subject:
          type: string
          minLength: 4
          example: 'TestSubject'
        description:
          type: string
          minLength: 4
          maxLength: 100
          example: 'My content'
        creator:
          type: string
          minLength: 4
          maxLength: 100
          example: 'LluisPetardo'
        creationdate:
          type: string
          format: date-time
        modifieddate:
          type: string
          format: date-time
        deadlinedate:
          type: string
          format: date-time
        deadlinemotive:
          type: string
          minLength: 4
          maxLength: 100
          example: 'PQ_LluisPetardo'
        blocked:
          type: boolean
        blockmotiv*e:
          type: string
          minLength: 4
          maxLength: 100
          example: 'PQ_LluisPetardo'
        deadline:
          type: boolean
        status:
          type: integer
          format: int64
          example: 2
        type:
          type: integer
          format: int64
          example: 2
        severity:
          type: integer
          format: int64
          example: 2
        priority:
          type: integer
          format: int64
          example: 2
        watchers:
          type: array
          items:
            $ref: '#/components/schemas/User'
        asignedTo:
          type: array
          items:
            $ref: '#/components/schemas/User'
        _links:
          type: object
          properties:
            self:
              type: string
              format: url
              example: 'http://127.0.0.1:8000/api/Issue/?Issue=1'