# Generated by Django 4.1.7 on 2023-04-11 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('type', models.IntegerField()),
                ('severity', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('modifieddate', models.DateTimeField(auto_now=True)),
                ('deadlinemotive', models.CharField(max_length=100)),
                ('blocked', models.BooleanField(default=False)),
                ('blockmotive', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.BooleanField(default=False)),
                ('deadlinedate', models.DateTimeField(null=True)),
                ('asignedTo', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blacklotus.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='Attachments/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blacklotus.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('field', models.CharField(max_length=100)),
                ('change', models.CharField(max_length=100)),
                ('old', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('issueChanged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blacklotus.issue')),
            ],
        ),
    ]
