# Generated by Django 4.1.7 on 2023-04-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklotus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='deadlinedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
