# Generated by Django 4.1.7 on 2023-04-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklotus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='br@br.cpm', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
