# Generated by Django 4.1.7 on 2023-04-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklotus', '0002_issue_asignedto_asignedto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignedTo',
        ),
    ]
