# Generated by Django 4.1.7 on 2023-04-11 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blacklotus', '0003_delete_asignedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='blockmotive',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='deadlinedate',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blacklotus.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('field', models.CharField(max_length=100)),
                ('change', models.CharField(max_length=100)),
                ('old', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('issueChanged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blacklotus.issue')),
            ],
        ),
    ]
