# Generated by Django 4.1.7 on 2023-04-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklotus', '0002_customuser_delete_user'),
        ('blacklotus', '0003_customuser_delete_user'),
    ]

    operations = [
    ]
